Gymkana/Gymkana/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('portal.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gymkana/portal/urls.py
from django.urls import path

from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('v1/news/create', views.create_new, name = 'new_form'),
    path('v1/news/<int:new_id>', views.read_new, name = 'read_new'),
    path('v1/news/<int:new_id>/edit', views.edit_new, name = 'edit_new'),
    path('v1/news/<int:new_id>/delete', views.delete_new, name = 'delete_new'),
    path('v2/news/create', views.create_new_class.as_view(), name = 'new_form_class'),
    path('v2/news/<int:pk>', views.read_new_class.as_view(), name = 'read_new_class'),
    path('v2/news/<int:pk>/edit', views.edit_new_class.as_view(), name = 'edit_new_class'),
    path('v2/news/<int:pk>/delete', views.delete_new_class.as_view(), name = 'delete_new_class'),
    path('v2/events/create', views.create_event_class.as_view(), name = 'event_form_class'),
    path('v2/events/<int:pk>', views.read_event_class.as_view(), name = 'read_event_class'),
    path('v2/events/<int:pk>/edit', views.edit_event_class.as_view(), name = 'edit_event_class'),
    path('v2/events/<int:pk>/delete', views.delete_event_class.as_view(), name = 'delete_event_class'),
    path('api/events/', views.event_APIView_create.as_view(), name='create_event_api'),
    path('api/events/<int:pk>', views.event_APIView_detail.as_view(), name='event_detail_api'),
    ]

Gymkana/portal/models.py
import os

from django.db import models
from django.dispatch import receiver
from django.utils import timezone

def path_and_rename(instance, filename):
        upload_to = ""
        name = filename.split('.')[0]
        ext = filename.split('.')[-1]
        now = instance.publish_date.strftime("%d-%m-%YT%H%M")
        filename = '{}{}.{}'.format(name, now, ext)
        return os.path.join(upload_to, filename)



class BaseItem(models.Model):
    title = models.CharField(max_length = 100, blank = False)
    subtitle = models.CharField(max_length = 200, blank = False)
    body = models.TextField(blank = False)

    class Meta:
        abstract = True

class New(BaseItem):
    publish_date = models.DateTimeField(default = timezone.now)
    image = models.ImageField(upload_to=path_and_rename, default ='default.jpg')

"""
Deletes file from filesystem
when corresponding `MediaFile` object is deleted.
"""
@receiver(models.signals.post_delete, sender=New)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.image and instance.image.name != 'default.jpg':
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

class Event(BaseItem):
    start_date = models.DateTimeField(null=False)
    end_date = models.DateTimeField(null=False)

Gymkana/portal/forms.py
from django import forms
from django.forms import widgets
from .models import Event, New

class NewForm(forms.ModelForm):
    
    class Meta:
        model = New
        fields = ['title', 'subtitle', 'body', 'image']

        labels = {
            'title': 'Título',
            'subtitle': 'Subtítulo',
            'body': 'Cuerpo',
            'image': 'Imagen'
        }

    def clean_image(self):
        image = self.cleaned_data['image']

        #Case we upload the image
        if type(image) != str:
            """
            We have to check the photo format is .jpg or .png
            """
            if not (image.name.endswith('.jpg') or image.name.endswith('.png')):
                raise forms.ValidationError('El formato debe ser JPG o PNG', code = 'invalid')

            """
            We have to limit the image size to 10MB
            """
            if image.size > 10000000:
                raise forms.ValidationError('Máximo 10 MB', code = 'heavy_img')

        return image

class EventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ['title', 'subtitle', 'body', 'start_date', 'end_date']

        labels = {
            'title': 'Título',
            'subtitle': 'Subtítulo',
            'body': 'Cuerpo',
            'start_date': 'Fecha de comienzo',
            'end_date': 'Fecha de fin'
        }

        widgets = {
            'start_date': widgets.DateInput(attrs={'type':'date'}),
            'end_date': widgets.DateInput(attrs={'type':'date'}),
        }

    def clean_end_date(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']

        """
        start_date must be before end_start
        """
        if start_date > end_date:
            raise forms.ValidationError('La fecha de comienzo no puede ser posterior a la fin', code = 'invalid_dates')

        return end_date

Gymkana/portal/views.py
import io
from django import utils

from django.urls.base import reverse_lazy

from portal.forms import NewForm, EventForm
from portal.models import Event, New
from django.utils import timezone
from django.views import generic
from django.shortcuts import get_object_or_404, redirect, render
from django.http.response import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext as _

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from portal import serializers

class IndexView(generic.ListView):
    """
    Main view of the proyect
    """
    template_name = 'portal/index.html'
    context_object_name = 'lastest_news_list'


    def get_queryset(self):
        """
    We just want to see our last three news as 'lastest_news_list'
    """
        return New.objects.filter(publish_date__lte = timezone.now()).order_by('-publish_date')[:3]

    def get_context_data(self, **kwargs):
        """
        We just want to see our next three news as 'next_events_list'
        """
        context = super().get_context_data(**kwargs)
        context['next_events_list'] = Event.objects.filter(end_date__gte = timezone.now()).order_by('-end_date')[:3]
        return context

"""
Creation of new in FBV
"""
def create_new(request):
    if request.method == 'POST':
        new_form = NewForm(request.POST, request.FILES)        
        if new_form.is_valid():
            new_form.save()
            return redirect('portal:index')

    else:
        new_form = NewForm()
    return render(request, 'portal/new_form.html', {'form':new_form})

"""
Read new in FBV
"""
def read_new(request, new_id):
    new = get_object_or_404(New, pk = new_id)
    return render(request, 'portal/read_new.html', {'new': new})

"""
Edit new in FBV
"""
def edit_new(request, new_id):
    new = get_object_or_404(New, pk = new_id)
    if request.method == 'POST':
        form = NewForm(request.POST or None, files =  request.FILES or None, instance = new)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('portal:read_new',  args=[new_id]))
    else:
        form = NewForm(instance = new, initial={'new_id': new_id})
    return render(request, 'portal/edit_new.html', {'form':form})

"""
Delte new FBV
"""
def delete_new(request, new_id):
    new = get_object_or_404(New, pk = new_id)
    if request.method == 'POST':
        new.delete()
        return HttpResponseRedirect(reverse('portal:index'))
    else:
        return render(request, 'portal/delete_form.html', {'new':new})

"""
Creation of new CBV
"""
class create_new_class(generic.CreateView):
    template_name = 'portal/new_form.html'
    form_class = NewForm
    success_url = '/'

"""
Read new with CBV
"""
class read_new_class(generic.DetailView):
    model = New
    template_name = 'portal/read_new.html'
    
"""
Creation of new CBV
"""
class edit_new_class(generic.UpdateView):
    model = New
    template_name = 'portal/edit_new.html'
    form_class = NewForm

    def get_success_url(self):
        return reverse('portal:read_new_class', kwargs = {'pk':self.object.id})

"""
Delete new with CBV
"""
class delete_new_class(generic.DeleteView):
    model = New
    success_url = '/'
    template_name = 'portal/delete_form.html'

"""
Create events with CBV
"""
class create_event_class(generic.CreateView):
    template_name = 'portal/event_form.html'
    form_class = EventForm
    success_url = '/'

"""
Read events with CBV
"""
class read_event_class(generic.DeleteView):
    model = Event
    template_name = 'portal/read_event.html'

"""
Edit events with CBV
"""
class edit_event_class(generic.UpdateView):
    model = Event
    template_name = 'portal/edit_event.html'
    form_class = EventForm

    def get_success_url(self):
        return reverse('portal:read_event_class', kwargs = {'pk':self.object.id})

"""
Delete events with CBV and a Modal window
"""
class delete_event_class(generic.DeleteView):
    model = Event
    success_url = '/'

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

"""
API methods for Events
"""
class event_APIView_create(APIView):

    serializer_class = serializers.event_serializer

    """
    Endpoint for Create an Event
    """
    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class event_APIView_detail(APIView):

    def get_object(self, pk):
            try:
                return Event.objects.get(pk=pk)
            except Event.DoesNotExist:
                raise Http404

    """
    Endpoint for Read an Event 
    """
    def get(self, request, pk, format=None):
        event = self.get_object(pk)
        serializer = serializers.event_serializer(event)
        return Response(serializer.data, status=status.HTTP_200_OK)

    """
    Endpoint for Edit an Event 
    """
    def put(self, request, pk, format=None):
        event = self.get_object(pk)
        serializer = serializers.event_serializer(event, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        event = self.get_object(pk)
        event.delete()
        return Response (status=status.HTTP_204_NO_CONTENT)

Gymkana/portal/templates/portal/base.html
{% load static %}

<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="{% static 'portal/style.css' %}">

<div id=navbar>
    <ul id="navbar"> 
        <li><a href="/">Gymkana Django</a></li>
        <li style="float: right; background-color: mediumvioletred;">v2</li>
        <li style="float: right; background-color: green;">v1</li>
      </ul>
</div>

{% block content %}
{% endblock %}

Gymkana/portal/templates/portal/delete_form.html
{% extends 'portal/base.html' %}
{% block content %}

<div class="form">
    <form method="POST">
        {% csrf_token %}
        <p style="text-align: center;">¿Esta seguro de que quiere eliminar la noticia?</p>
        <button type = "submit" style="margin-left: 50%;">Confirmar</button>
    </form>
</div>


{% endblock %}

Gymkana/portal/templates/portal/edit_event.html
{% extends 'portal/base.html' %}
{% block content %}

<div class="form">
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type = "submit">Editar</button>
    </form>
</div>

{% endblock %}

Gymkana/portal/templates/portal/edit_new.html
{% extends 'portal/base.html' %}
{% block content %}

<div class="form">
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type = "submit">Editar</button>
    </form>
</div>


{% endblock %}

Gymkana/portal/templates/portal/event_form.html
{% extends 'portal/base.html' %}
{% block content %}

<div class="form">
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type = "submit">Añadir</button>
    </form>
</div>

{% endblock %}

Gymkana/portal/templates/portal/index.html
{% extends 'portal/base.html' %}
{% block content %}
{% load i18n %}

<div class="content">
    <div class="container" id="news">
        <h3 style="display: inline;" class="title_section">{% trans "Últimas noticias" %}</h3>
        
            <a id="form_button" href="{% url 'portal:new_form' %}" style="margin-left: 5%;">
                <button style="background-color: green;">{% trans "Nueva noticia" %}</button>
            </a>
            <a id="form_button" href="{% url 'portal:new_form_class' %}" style="margin-left: 5%;">
                <button style="background-color: mediumvioletred;">{% trans "Nueva noticia" %}</button>
            </a>
        {% if lastest_news_list %}
        <table>
            {% for new in lastest_news_list%}
            <tr class="clickable-row" data-href="v1/news/{{ new.id }}">
                <td>
                    <h2> {{ new.title }} </h2>
                    <p>{{ new.subtitle }}</p>
                </td>
                <td style="text-align: center; width: 7%;"><a id="form_button" href="{% url 'portal:read_new' new.id %}" style="margin-left: 5%;">
                    <button style="background-color: green;">{% trans "Leer" %}</button>
                </a></td>
                <td style="text-align: center; width: 7%;"><a id="form_button" href="{% url 'portal:read_new_class' new.id %}" style="margin-left: 5%;">
                    <button style="background-color: mediumvioletred;">{% trans "Leer" %}</button>
                </a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
            <p>No hay noticias disponibles</p>
            
        {% endif %}
    </div>
    
    <div class="container" id="events" style="margin-top: 3%;">
        <h3 style="display: inline;" class="title_section">{% trans "Próximos eventos" %}</h3>
        <a id="form_button" href="{% url 'portal:event_form_class' %}" style="margin-left: 5%;">
            <button style="background-color: mediumvioletred;">{% trans "Nuevo evento" %}</button>
        </a>
        {% if next_events_list %}
        <table>
            {% for event in next_events_list%}
            <tr class="clickable-row" data-href="v1/events/{{ event.id }}">
                <td>
                    <h2> {{ event.title }} </h2>
                    <p>{{ event.start_date }}</p>
                </td>
                <td style="text-align: center; width: 7%;"><a id="form_button" href="{% url 'portal:read_event_class' event.id %}">
                    <button style="background-color: mediumvioletred;">{% trans "Leer" %}</button>
                </a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
            <p>No hay eventos disponibles</p>
        {% endif %}
    </div>
    
</div>
{% endblock %}

Gymkana/portal/templates/portal/new_form.html
{% extends 'portal/base.html' %}
{% block content %}

<div class="form">
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type = "submit">Añadir</button>
    </form>
</div>

{% endblock %}

Gymkana/portal/templates/portal/read_event.html
{% extends 'portal/base.html' %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script> 

<script type="text/javascript">
    $(document).ready(function() {
        $('#delete_event').on("click", function() {
        var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
        if (window.confirm("¿Desea eliminar el evento?")) { 
            $.post("v2/events{{event.id}}/delete/",{
                csrfmiddlewaretoken: CSRFtoken
            });
        }
        });
    });
</script>

<div style="margin-left: 5%; margin-right: 5%;">

    <div style="text-align: center;">
        <h1>{{ event.title }}</h1>
    </div>

    <div>
        <h4>{{ event.subtitle }}</h4>
    </div>

    <div style="text-align: center;">
        <p style="font-size: x-large;">{{ event.start_date }} - {{ event.end_date }}</p>
    </div>

    <div>
        <p>{{ event.body }}</p>
    </div>

    <a id="form_button" href="{% url 'portal:edit_event_class' event.id %}" style="float: right;">
        <button style="background-color: mediumvioletred;">Editar</button>
    </a>

    <a id="delete_event" href="{% url 'portal:delete_event_class' event.id %}" style="float: right;">
        <button style="background-color: mediumvioletred;">Eliminar</button>
    </a>    

</div>
{% endblock %}

Gymkana/portal/templates/portal/read_new.html
{% extends 'portal/base.html' %}
{% block content %}

<div style="margin-left: 5%; margin-right: 5%;">

    <div style="text-align: center;">
        <h1>{{ new.title }}</h1>
    </div>

    <div style="text-align: center;">
        <img src="/media/{{ new.image }}" alt="{{ new.image }}">
    </div>
    
    <div>
        <h4>{{ new.subtitle }}</h4>
    </div>

    <div style="text-align: right;">
        <p style="font-size: small;">{{ new.publish_date }}</p>
    </div>

    <div>
        <p>{{ new.body }}</p>
    </div>

    <a id="form_button" href="{% url 'portal:edit_new_class' new.id %}" style="float: left;">
        <button style="background-color: mediumvioletred;">Editar</button>
    </a>

    <a id="form_button" href="{% url 'portal:delete_new_class' new.id %}" style="float: left;">
        <button style="background-color: mediumvioletred;">Eliminar</button>
    </a>

    <a id="form_button" href="{% url 'portal:delete_new' new.id %}" style="float: right;">
        <button style="background-color: green;">Eliminar</button>
    </a>

    <a id="form_button" href="{% url 'portal:edit_new' new.id %}" style="float: right;">
        <button style="background-color: green;">Editar</button>
    </a>
        
</div>
{% endblock %}